# Generated by Django 3.0.5 on 2020-04-04 22:04

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('body_text', markdownx.models.MarkdownxField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
