# Generated by Django 3.0.5 on 2020-04-05 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200405_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='leader_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 17, 13, 28, 109115), verbose_name='date published'),
        ),
    ]
